graph TB
    x00[/x00/]
    x01[/x01/]
    x02[/x02/]
    x03[/x03/]
    x04[/x04/]
    x05[/x05/]
    x06[/x06/]
    x07[/x07/]
    x08[/x08/]
    x09[/x09/]
    x10[/x10/]
    x11[/x11/]
    x12[/x12/]
    x13[/x13/]
    x14[/x14/]
    x15[/x15/]
    x16[/x16/]
    x17[/x17/]
    x18[/x18/]
    x19[/x19/]
    x20[/x20/]
    x21[/x21/]
    x22[/x22/]
    x23[/x23/]
    x24[/x24/]
    x25[/x25/]
    x26[/x26/]
    x27[/x27/]
    x28[/x28/]
    x29[/x29/]
    x30[/x30/]
    x31[/x31/]
    x32[/x32/]
    x33[/x33/]
    x34[/x34/]
    x35[/x35/]
    x36[/x36/]
    x37[/x37/]
    x38[/x38/]
    x39[/x39/]
    x40[/x40/]
    x41[/x41/]
    x42[/x42/]
    x43[/x43/]
    x44[/x44/]
    y00[/y00/]
    y01[/y01/]
    y02[/y02/]
    y03[/y03/]
    y04[/y04/]
    y05[/y05/]
    y06[/y06/]
    y07[/y07/]
    y08[/y08/]
    y09[/y09/]
    y10[/y10/]
    y11[/y11/]
    y12[/y12/]
    y13[/y13/]
    y14[/y14/]
    y15[/y15/]
    y16[/y16/]
    y17[/y17/]
    y18[/y18/]
    y19[/y19/]
    y20[/y20/]
    y21[/y21/]
    y22[/y22/]
    y23[/y23/]
    y24[/y24/]
    y25[/y25/]
    y26[/y26/]
    y27[/y27/]
    y28[/y28/]
    y29[/y29/]
    y30[/y30/]
    y31[/y31/]
    y32[/y32/]
    y33[/y33/]
    y34[/y34/]
    y35[/y35/]
    y36[/y36/]
    y37[/y37/]
    y38[/y38/]
    y39[/y39/]
    y40[/y40/]
    y41[/y41/]
    y42[/y42/]
    y43[/y43/]
    y44[/y44/]
    gate_y34_XOR_x34[(=1)]
    y34 --> gate_y34_XOR_x34
    x34 --> gate_y34_XOR_x34
    gate_y34_XOR_x34 --> rgh
    rgh[[rgh]]
    gate_fcr_XOR_pqc[(=1)]
    fcr --> gate_fcr_XOR_pqc
    pqc --> gate_fcr_XOR_pqc
    gate_fcr_XOR_pqc --> z14
    z14[[z14]]
    gate_y23_AND_x23[(&)]
    y23 --> gate_y23_AND_x23
    x23 --> gate_y23_AND_x23
    gate_y23_AND_x23 --> cms
    cms[[cms]]
    gate_rkw_AND_shk[(&)]
    rkw --> gate_rkw_AND_shk
    shk --> gate_rkw_AND_shk
    gate_rkw_AND_shk --> pbq
    pbq[[pbq]]
    gate_x43_XOR_y43[(=1)]
    x43 --> gate_x43_XOR_y43
    y43 --> gate_x43_XOR_y43
    gate_x43_XOR_y43 --> jfh
    jfh[[jfh]]
    gate_y13_AND_x13[(&)]
    y13 --> gate_y13_AND_x13
    x13 --> gate_y13_AND_x13
    gate_y13_AND_x13 --> skt
    skt[[skt]]
    gate_hsd_OR_sng[(≥1)]
    hsd --> gate_hsd_OR_sng
    sng --> gate_hsd_OR_sng
    gate_hsd_OR_sng --> z45
    z45[[z45]]
    gate_vpv_AND_ddq[(&)]
    vpv --> gate_vpv_AND_ddq
    ddq --> gate_vpv_AND_ddq
    gate_vpv_AND_ddq --> bjr
    bjr[[bjr]]
    gate_shk_XOR_rkw[(=1)]
    shk --> gate_shk_XOR_rkw
    rkw --> gate_shk_XOR_rkw
    gate_shk_XOR_rkw --> z04
    z04[[z04]]
    gate_hnw_AND_gvs[(&)]
    hnw --> gate_hnw_AND_gvs
    gvs --> gate_hnw_AND_gvs
    gate_hnw_AND_gvs --> vdr
    vdr[[vdr]]
    gate_x08_AND_y08[(&)]
    x08 --> gate_x08_AND_y08
    y08 --> gate_x08_AND_y08
    gate_x08_AND_y08 --> htn
    htn[[htn]]
    gate_bcp_AND_rgc[(&)]
    bcp --> gate_bcp_AND_rgc
    rgc --> gate_bcp_AND_rgc
    gate_bcp_AND_rgc --> pbh
    pbh[[pbh]]
    gate_y20_AND_x20[(&)]
    y20 --> gate_y20_AND_x20
    x20 --> gate_y20_AND_x20
    gate_y20_AND_x20 --> ccp
    ccp[[ccp]]
    gate_x10_XOR_y10[(=1)]
    x10 --> gate_x10_XOR_y10
    y10 --> gate_x10_XOR_y10
    gate_x10_XOR_y10 --> ggd
    ggd[[ggd]]
    gate_qfb_OR_snk[(≥1)]
    qfb --> gate_qfb_OR_snk
    snk --> gate_qfb_OR_snk
    gate_qfb_OR_snk --> kmn
    kmn[[kmn]]
    gate_y24_XOR_x24[(=1)]
    y24 --> gate_y24_XOR_x24
    x24 --> gate_y24_XOR_x24
    gate_y24_XOR_x24 --> rjm
    rjm[[rjm]]
    gate_vdr_OR_dkd[(≥1)]
    vdr --> gate_vdr_OR_dkd
    dkd --> gate_vdr_OR_dkd
    gate_vdr_OR_dkd --> pmm
    pmm[[pmm]]
    gate_pmm_XOR_vgm[(=1)]
    pmm --> gate_pmm_XOR_vgm
    vgm --> gate_pmm_XOR_vgm
    gate_pmm_XOR_vgm --> z26
    z26[[z26]]
    gate_x32_AND_y32[(&)]
    x32 --> gate_x32_AND_y32
    y32 --> gate_x32_AND_y32
    gate_x32_AND_y32 --> htq
    htq[[htq]]
    gate_bgs_OR_dvp[(≥1)]
    bgs --> gate_bgs_OR_dvp
    dvp --> gate_bgs_OR_dvp
    gate_bgs_OR_dvp --> vdd
    vdd[[vdd]]
    gate_vdd_AND_dgk[(&)]
    vdd --> gate_vdd_AND_dgk
    dgk --> gate_vdd_AND_dgk
    gate_vdd_AND_dgk --> wdr
    wdr[[wdr]]
    gate_y44_AND_x44[(&)]
    y44 --> gate_y44_AND_x44
    x44 --> gate_y44_AND_x44
    gate_y44_AND_x44 --> sng
    sng[[sng]]
    gate_jtd_AND_qwj[(&)]
    jtd --> gate_jtd_AND_qwj
    qwj --> gate_jtd_AND_qwj
    gate_jtd_AND_qwj --> bsf
    bsf[[bsf]]
    gate_dgm_OR_cth[(≥1)]
    dgm --> gate_dgm_OR_cth
    cth --> gate_dgm_OR_cth
    gate_dgm_OR_cth --> msm
    msm[[msm]]
    gate_cft_AND_gsf[(&)]
    cft --> gate_cft_AND_gsf
    gsf --> gate_cft_AND_gsf
    gate_cft_AND_gsf --> nhd
    nhd[[nhd]]
    gate_dsw_OR_pmr[(≥1)]
    dsw --> gate_dsw_OR_pmr
    pmr --> gate_dsw_OR_pmr
    gate_dsw_OR_pmr --> pgq
    pgq[[pgq]]
    gate_msm_AND_fdm[(&)]
    msm --> gate_msm_AND_fdm
    fdm --> gate_msm_AND_fdm
    gate_msm_AND_fdm --> cwb
    cwb[[cwb]]
    gate_y16_AND_x16[(&)]
    y16 --> gate_y16_AND_x16
    x16 --> gate_y16_AND_x16
    gate_y16_AND_x16 --> ffm
    ffm[[ffm]]
    gate_y33_XOR_x33[(=1)]
    y33 --> gate_y33_XOR_x33
    x33 --> gate_y33_XOR_x33
    gate_y33_XOR_x33 --> mrp
    mrp[[mrp]]
    gate_y17_XOR_x17[(=1)]
    y17 --> gate_y17_XOR_x17
    x17 --> gate_y17_XOR_x17
    gate_y17_XOR_x17 --> vcs
    vcs[[vcs]]
    gate_hcg_OR_cwb[(≥1)]
    hcg --> gate_hcg_OR_cwb
    cwb --> gate_hcg_OR_cwb
    gate_hcg_OR_cwb --> djr
    djr[[djr]]
    gate_phn_AND_wph[(&)]
    phn --> gate_phn_AND_wph
    wph --> gate_phn_AND_wph
    gate_phn_AND_wph --> cgf
    cgf[[cgf]]
    gate_ggd_XOR_dfm[(=1)]
    ggd --> gate_ggd_XOR_dfm
    dfm --> gate_ggd_XOR_dfm
    gate_ggd_XOR_dfm --> z10
    z10[[z10]]
    gate_pgq_AND_dwq[(&)]
    pgq --> gate_pgq_AND_dwq
    dwq --> gate_pgq_AND_dwq
    gate_pgq_AND_dwq --> wpp
    wpp[[wpp]]
    gate_wvr_AND_gpq[(&)]
    wvr --> gate_wvr_AND_gpq
    gpq --> gate_wvr_AND_gpq
    gate_wvr_AND_gpq --> hsd
    hsd[[hsd]]
    gate_x31_XOR_y31[(=1)]
    x31 --> gate_x31_XOR_y31
    y31 --> gate_x31_XOR_y31
    gate_x31_XOR_y31 --> kqk
    kqk[[kqk]]
    gate_qqt_AND_vdb[(&)]
    qqt --> gate_qqt_AND_vdb
    vdb --> gate_qqt_AND_vdb
    gate_qqt_AND_vdb --> mrt
    mrt[[mrt]]
    gate_x04_AND_y04[(&)]
    x04 --> gate_x04_AND_y04
    y04 --> gate_x04_AND_y04
    gate_x04_AND_y04 --> dpv
    dpv[[dpv]]
    gate_y17_AND_x17[(&)]
    y17 --> gate_y17_AND_x17
    x17 --> gate_y17_AND_x17
    gate_y17_AND_x17 --> vfn
    vfn[[vfn]]
    gate_y11_AND_x11[(&)]
    y11 --> gate_y11_AND_x11
    x11 --> gate_y11_AND_x11
    gate_y11_AND_x11 --> wmn
    wmn[[wmn]]
    gate_x26_AND_y26[(&)]
    x26 --> gate_x26_AND_y26
    y26 --> gate_x26_AND_y26
    gate_x26_AND_y26 --> dmw
    dmw[[dmw]]
    gate_y30_XOR_x30[(=1)]
    y30 --> gate_y30_XOR_x30
    x30 --> gate_y30_XOR_x30
    gate_y30_XOR_x30 --> fdm
    fdm[[fdm]]
    gate_y19_XOR_x19[(=1)]
    y19 --> gate_y19_XOR_x19
    x19 --> gate_y19_XOR_x19
    gate_y19_XOR_x19 --> tqj
    tqj[[tqj]]
    gate_cft_XOR_gsf[(=1)]
    cft --> gate_cft_XOR_gsf
    gsf --> gate_cft_XOR_gsf
    gate_cft_XOR_gsf --> z11
    z11[[z11]]
    gate_djr_XOR_kqk[(=1)]
    djr --> gate_djr_XOR_kqk
    kqk --> gate_djr_XOR_kqk
    gate_djr_XOR_kqk --> bgs
    bgs[[bgs]]
    gate_rjm_AND_ktp[(&)]
    rjm --> gate_rjm_AND_ktp
    ktp --> gate_rjm_AND_ktp
    gate_rjm_AND_ktp --> pwn
    pwn[[pwn]]
    gate_chd_AND_mrp[(&)]
    chd --> gate_chd_AND_mrp
    mrp --> gate_chd_AND_mrp
    gate_chd_AND_mrp --> cwg
    cwg[[cwg]]
    gate_rgh_XOR_nng[(=1)]
    rgh --> gate_rgh_XOR_nng
    nng --> gate_rgh_XOR_nng
    gate_rgh_XOR_nng --> z34
    z34[[z34]]
    gate_x27_AND_y27[(&)]
    x27 --> gate_x27_AND_y27
    y27 --> gate_x27_AND_y27
    gate_x27_AND_y27 --> mgt
    mgt[[mgt]]
    gate_jfh_AND_kmm[(&)]
    jfh --> gate_jfh_AND_kmm
    kmm --> gate_jfh_AND_kmm
    gate_jfh_AND_kmm --> scm
    scm[[scm]]
    gate_psj_XOR_qbn[(=1)]
    psj --> gate_psj_XOR_qbn
    qbn --> gate_psj_XOR_qbn
    gate_psj_XOR_qbn --> z29
    z29[[z29]]
    gate_x14_AND_y14[(&)]
    x14 --> gate_x14_AND_y14
    y14 --> gate_x14_AND_y14
    gate_x14_AND_y14 --> bsd
    bsd[[bsd]]
    gate_x12_XOR_y12[(=1)]
    x12 --> gate_x12_XOR_y12
    y12 --> gate_x12_XOR_y12
    gate_x12_XOR_y12 --> bqw
    bqw[[bqw]]
    gate_vgj_AND_pms[(&)]
    vgj --> gate_vgj_AND_pms
    pms --> gate_vgj_AND_pms
    gate_vgj_AND_pms --> cjw
    cjw[[cjw]]
    gate_cwg_OR_vjs[(≥1)]
    cwg --> gate_cwg_OR_vjs
    vjs --> gate_cwg_OR_vjs
    gate_cwg_OR_vjs --> nng
    nng[[nng]]
    gate_wpv_XOR_cwh[(=1)]
    wpv --> gate_wpv_XOR_cwh
    cwh --> gate_wpv_XOR_cwh
    gate_wpv_XOR_cwh --> z36
    z36[[z36]]
    gate_x43_AND_y43[(&)]
    x43 --> gate_x43_AND_y43
    y43 --> gate_x43_AND_y43
    gate_x43_AND_y43 --> htd
    htd[[htd]]
    gate_x02_XOR_y02[(=1)]
    x02 --> gate_x02_XOR_y02
    y02 --> gate_x02_XOR_y02
    gate_x02_XOR_y02 --> wsw
    wsw[[wsw]]
    gate_vdb_XOR_qqt[(=1)]
    vdb --> gate_vdb_XOR_qqt
    qqt --> gate_vdb_XOR_qqt
    gate_vdb_XOR_qqt --> z28
    z28[[z28]]
    gate_bwr_OR_vqn[(≥1)]
    bwr --> gate_bwr_OR_vqn
    vqn --> gate_bwr_OR_vqn
    gate_bwr_OR_vqn --> bqd
    bqd[[bqd]]
    gate_y38_XOR_x38[(=1)]
    y38 --> gate_y38_XOR_x38
    x38 --> gate_y38_XOR_x38
    gate_y38_XOR_x38 --> dtr
    dtr[[dtr]]
    gate_qgc_XOR_kfh[(=1)]
    qgc --> gate_qgc_XOR_kfh
    kfh --> gate_qgc_XOR_kfh
    gate_qgc_XOR_kfh --> z06
    z06[[z06]]
    gate_x27_XOR_y27[(=1)]
    x27 --> gate_x27_XOR_y27
    y27 --> gate_x27_XOR_y27
    gate_x27_XOR_y27 --> cdb
    cdb[[cdb]]
    gate_x31_AND_y31[(&)]
    x31 --> gate_x31_AND_y31
    y31 --> gate_x31_AND_y31
    gate_x31_AND_y31 --> dvp
    dvp[[dvp]]
    gate_y00_XOR_x00[(=1)]
    y00 --> gate_y00_XOR_x00
    x00 --> gate_y00_XOR_x00
    gate_y00_XOR_x00 --> z00
    z00[[z00]]
    gate_wmn_OR_nhd[(≥1)]
    wmn --> gate_wmn_OR_nhd
    nhd --> gate_wmn_OR_nhd
    gate_wmn_OR_nhd --> mnh
    mnh[[mnh]]
    gate_rrf_XOR_qnw[(=1)]
    rrf --> gate_rrf_XOR_qnw
    qnw --> gate_rrf_XOR_qnw
    gate_rrf_XOR_qnw --> z35
    z35[[z35]]
    gate_vjb_OR_mrt[(≥1)]
    vjb --> gate_vjb_OR_mrt
    mrt --> gate_vjb_OR_mrt
    gate_vjb_OR_mrt --> psj
    psj[[psj]]
    gate_x21_XOR_y21[(=1)]
    x21 --> gate_x21_XOR_y21
    y21 --> gate_x21_XOR_y21
    gate_x21_XOR_y21 --> cbv
    cbv[[cbv]]
    gate_vcs_XOR_bfg[(=1)]
    vcs --> gate_vcs_XOR_bfg
    bfg --> gate_vcs_XOR_bfg
    gate_vcs_XOR_bfg --> z17
    z17[[z17]]
    gate_csb_XOR_pfg[(=1)]
    csb --> gate_csb_XOR_pfg
    pfg --> gate_csb_XOR_pfg
    gate_csb_XOR_pfg --> z16
    z16[[z16]]
    gate_wps_AND_kmn[(&)]
    wps --> gate_wps_AND_kmn
    kmn --> gate_wps_AND_kmn
    gate_wps_AND_kmn --> pvw
    pvw[[pvw]]
    gate_bcp_XOR_rgc[(=1)]
    bcp --> gate_bcp_XOR_rgc
    rgc --> gate_bcp_XOR_rgc
    gate_bcp_XOR_rgc --> z08
    z08[[z08]]
    gate_vgm_AND_pmm[(&)]
    vgm --> gate_vgm_AND_pmm
    pmm --> gate_vgm_AND_pmm
    gate_vgm_AND_pmm --> sbq
    sbq[[sbq]]
    gate_y14_XOR_x14[(=1)]
    y14 --> gate_y14_XOR_x14
    x14 --> gate_y14_XOR_x14
    gate_y14_XOR_x14 --> fcr
    fcr[[fcr]]
    gate_pbh_OR_htn[(≥1)]
    pbh --> gate_pbh_OR_htn
    htn --> gate_pbh_OR_htn
    gate_pbh_OR_htn --> ddq
    ddq[[ddq]]
    gate_rcd_XOR_rqt[(=1)]
    rcd --> gate_rcd_XOR_rqt
    rqt --> gate_rcd_XOR_rqt
    gate_rcd_XOR_rqt --> z37
    z37[[z37]]
    gate_y18_XOR_x18[(=1)]
    y18 --> gate_y18_XOR_x18
    x18 --> gate_y18_XOR_x18
    gate_y18_XOR_x18 --> gbv
    gbv[[gbv]]
    gate_y02_AND_x02[(&)]
    y02 --> gate_y02_AND_x02
    x02 --> gate_y02_AND_x02
    gate_y02_AND_x02 --> snk
    snk[[snk]]
    gate_x06_XOR_y06[(=1)]
    x06 --> gate_x06_XOR_y06
    y06 --> gate_x06_XOR_y06
    gate_x06_XOR_y06 --> qgc
    qgc[[qgc]]
    gate_y06_AND_x06[(&)]
    y06 --> gate_y06_AND_x06
    x06 --> gate_y06_AND_x06
    gate_y06_AND_x06 --> mwg
    mwg[[mwg]]
    gate_x34_AND_y34[(&)]
    x34 --> gate_x34_AND_y34
    y34 --> gate_x34_AND_y34
    gate_x34_AND_y34 --> fvp
    fvp[[fvp]]
    gate_x35_AND_y35[(&)]
    x35 --> gate_x35_AND_y35
    y35 --> gate_x35_AND_y35
    gate_x35_AND_y35 --> tnt
    tnt[[tnt]]
    gate_chd_XOR_mrp[(=1)]
    chd --> gate_chd_XOR_mrp
    mrp --> gate_chd_XOR_mrp
    gate_chd_XOR_mrp --> z33
    z33[[z33]]
    gate_nnt_AND_cbv[(&)]
    nnt --> gate_nnt_AND_cbv
    cbv --> gate_nnt_AND_cbv
    gate_nnt_AND_cbv --> mcs
    mcs[[mcs]]
    gate_tmr_XOR_pnf[(=1)]
    tmr --> gate_tmr_XOR_pnf
    pnf --> gate_tmr_XOR_pnf
    gate_tmr_XOR_pnf --> z05
    z05[[z05]]
    gate_x29_AND_y29[(&)]
    x29 --> gate_x29_AND_y29
    y29 --> gate_x29_AND_y29
    gate_x29_AND_y29 --> dgm
    dgm[[dgm]]
    gate_x42_AND_y42[(&)]
    x42 --> gate_x42_AND_y42
    y42 --> gate_x42_AND_y42
    gate_x42_AND_y42 --> bnc
    bnc[[bnc]]
    gate_msm_XOR_fdm[(=1)]
    msm --> gate_msm_XOR_fdm
    fdm --> gate_msm_XOR_fdm
    gate_msm_XOR_fdm --> z30
    z30[[z30]]
    gate_ppf_OR_ffm[(≥1)]
    ppf --> gate_ppf_OR_ffm
    ffm --> gate_ppf_OR_ffm
    gate_ppf_OR_ffm --> bfg
    bfg[[bfg]]
    gate_nnh_OR_bjr[(≥1)]
    nnh --> gate_nnh_OR_bjr
    bjr --> gate_nnh_OR_bjr
    gate_nnh_OR_bjr --> dfm
    dfm[[dfm]]
    gate_cdb_AND_rtm[(&)]
    cdb --> gate_cdb_AND_rtm
    rtm --> gate_cdb_AND_rtm
    gate_cdb_AND_rtm --> cdw
    cdw[[cdw]]
    gate_ccp_OR_vtg[(≥1)]
    ccp --> gate_ccp_OR_vtg
    vtg --> gate_ccp_OR_vtg
    gate_ccp_OR_vtg --> nnt
    nnt[[nnt]]
    gate_kpv_XOR_rvc[(=1)]
    kpv --> gate_kpv_XOR_rvc
    rvc --> gate_kpv_XOR_rvc
    gate_kpv_XOR_rvc --> z07
    z07[[z07]]
    gate_y15_AND_x15[(&)]
    y15 --> gate_y15_AND_x15
    x15 --> gate_y15_AND_x15
    gate_y15_AND_x15 --> kgh
    kgh[[kgh]]
    gate_kqk_AND_djr[(&)]
    kqk --> gate_kqk_AND_djr
    djr --> gate_kqk_AND_djr
    gate_kqk_AND_djr --> z31
    z31[[z31]]
    gate_tqj_XOR_frj[(=1)]
    tqj --> gate_tqj_XOR_frj
    frj --> gate_tqj_XOR_frj
    gate_tqj_XOR_frj --> z19
    z19[[z19]]
    gate_x01_AND_y01[(&)]
    x01 --> gate_x01_AND_y01
    y01 --> gate_x01_AND_y01
    gate_x01_AND_y01 --> hhp
    hhp[[hhp]]
    gate_pfg_AND_csb[(&)]
    pfg --> gate_pfg_AND_csb
    csb --> gate_pfg_AND_csb
    gate_pfg_AND_csb --> ppf
    ppf[[ppf]]
    gate_y20_XOR_x20[(=1)]
    y20 --> gate_y20_XOR_x20
    x20 --> gate_y20_XOR_x20
    gate_y20_XOR_x20 --> ddh
    ddh[[ddh]]
    gate_y44_XOR_x44[(=1)]
    y44 --> gate_y44_XOR_x44
    x44 --> gate_y44_XOR_x44
    gate_y44_XOR_x44 --> wvr
    wvr[[wvr]]
    gate_ngw_OR_srm[(≥1)]
    ngw --> gate_ngw_OR_srm
    srm --> gate_ngw_OR_srm
    gate_ngw_OR_srm --> frj
    frj[[frj]]
    gate_x03_XOR_y03[(=1)]
    x03 --> gate_x03_XOR_y03
    y03 --> gate_x03_XOR_y03
    gate_x03_XOR_y03 --> wps
    wps[[wps]]
    gate_pgt_XOR_hbv[(=1)]
    pgt --> gate_pgt_XOR_hbv
    hbv --> gate_pgt_XOR_hbv
    gate_pgt_XOR_hbv --> z23
    z23[[z23]]
    gate_nng_AND_rgh[(&)]
    nng --> gate_nng_AND_rgh
    rgh --> gate_nng_AND_rgh
    gate_nng_AND_rgh --> npf
    npf[[npf]]
    gate_y28_AND_x28[(&)]
    y28 --> gate_y28_AND_x28
    x28 --> gate_y28_AND_x28
    gate_y28_AND_x28 --> vjb
    vjb[[vjb]]
    gate_bmc_AND_wsw[(&)]
    bmc --> gate_bmc_AND_wsw
    wsw --> gate_bmc_AND_wsw
    gate_bmc_AND_wsw --> qfb
    qfb[[qfb]]
    gate_y40_XOR_x40[(=1)]
    y40 --> gate_y40_XOR_x40
    x40 --> gate_y40_XOR_x40
    gate_y40_XOR_x40 --> bps
    bps[[bps]]
    gate_nnt_XOR_cbv[(=1)]
    nnt --> gate_nnt_XOR_cbv
    cbv --> gate_nnt_XOR_cbv
    gate_nnt_XOR_cbv --> z21
    z21[[z21]]
    gate_y26_XOR_x26[(=1)]
    y26 --> gate_y26_XOR_x26
    x26 --> gate_y26_XOR_x26
    gate_y26_XOR_x26 --> vgm
    vgm[[vgm]]
    gate_x37_AND_y37[(&)]
    x37 --> gate_x37_AND_y37
    y37 --> gate_x37_AND_y37
    gate_x37_AND_y37 --> khs
    khs[[khs]]
    gate_djt_OR_sbf[(≥1)]
    djt --> gate_djt_OR_sbf
    sbf --> gate_djt_OR_sbf
    gate_djt_OR_sbf --> kfh
    kfh[[kfh]]
    gate_npf_OR_fvp[(≥1)]
    npf --> gate_npf_OR_fvp
    fvp --> gate_npf_OR_fvp
    gate_npf_OR_fvp --> rrf
    rrf[[rrf]]
    gate_qsm_XOR_bqd[(=1)]
    qsm --> gate_qsm_XOR_bqd
    bqd --> gate_qsm_XOR_bqd
    gate_qsm_XOR_bqd --> z42
    z42[[z42]]
    gate_cff_OR_rbw[(≥1)]
    cff --> gate_cff_OR_rbw
    rbw --> gate_cff_OR_rbw
    gate_cff_OR_rbw --> qbf
    qbf[[qbf]]
    gate_x05_AND_y05[(&)]
    x05 --> gate_x05_AND_y05
    y05 --> gate_x05_AND_y05
    gate_x05_AND_y05 --> sbf
    sbf[[sbf]]
    gate_cdb_XOR_rtm[(=1)]
    cdb --> gate_cdb_XOR_rtm
    rtm --> gate_cdb_XOR_rtm
    gate_cdb_XOR_rtm --> z27
    z27[[z27]]
    gate_x22_AND_y22[(&)]
    x22 --> gate_x22_AND_y22
    y22 --> gate_x22_AND_y22
    gate_x22_AND_y22 --> fmg
    fmg[[fmg]]
    gate_bsd_OR_cpf[(≥1)]
    bsd --> gate_bsd_OR_cpf
    cpf --> gate_bsd_OR_cpf
    gate_bsd_OR_cpf --> phn
    phn[[phn]]
    gate_x42_XOR_y42[(=1)]
    x42 --> gate_x42_XOR_y42
    y42 --> gate_x42_XOR_y42
    gate_x42_XOR_y42 --> qsm
    qsm[[qsm]]
    gate_y13_XOR_x13[(=1)]
    y13 --> gate_y13_XOR_x13
    x13 --> gate_y13_XOR_x13
    gate_y13_XOR_x13 --> dwq
    dwq[[dwq]]
    gate_pqc_AND_fcr[(&)]
    pqc --> gate_pqc_AND_fcr
    fcr --> gate_pqc_AND_fcr
    gate_pqc_AND_fcr --> cpf
    cpf[[cpf]]
    gate_thc_XOR_brj[(=1)]
    thc --> gate_thc_XOR_brj
    brj --> gate_thc_XOR_brj
    gate_thc_XOR_brj --> z01
    z01[[z01]]
    gate_wvr_XOR_gpq[(=1)]
    wvr --> gate_wvr_XOR_gpq
    gpq --> gate_wvr_XOR_gpq
    gate_wvr_XOR_gpq --> z44
    z44[[z44]]
    gate_qgc_AND_kfh[(&)]
    qgc --> gate_qgc_AND_kfh
    kfh --> gate_qgc_AND_kfh
    gate_qgc_AND_kfh --> cfw
    cfw[[cfw]]
    gate_dtr_AND_brm[(&)]
    dtr --> gate_dtr_AND_brm
    brm --> gate_dtr_AND_brm
    gate_dtr_AND_brm --> rft
    rft[[rft]]
    gate_cfw_OR_mwg[(≥1)]
    cfw --> gate_cfw_OR_mwg
    mwg --> gate_cfw_OR_mwg
    gate_cfw_OR_mwg --> rvc
    rvc[[rvc]]
    gate_rft_OR_ncq[(≥1)]
    rft --> gate_rft_OR_ncq
    ncq --> gate_rft_OR_ncq
    gate_rft_OR_ncq --> qwj
    qwj[[qwj]]
    gate_x25_AND_y25[(&)]
    x25 --> gate_x25_AND_y25
    y25 --> gate_x25_AND_y25
    gate_x25_AND_y25 --> dkd
    dkd[[dkd]]
    gate_rhn_OR_nmm[(≥1)]
    rhn --> gate_rhn_OR_nmm
    nmm --> gate_rhn_OR_nmm
    gate_rhn_OR_nmm --> gnd
    gnd[[gnd]]
    gate_tqj_AND_frj[(&)]
    tqj --> gate_tqj_AND_frj
    frj --> gate_tqj_AND_frj
    gate_tqj_AND_frj --> rhn
    rhn[[rhn]]
    gate_jtd_XOR_qwj[(=1)]
    jtd --> gate_jtd_XOR_qwj
    qwj --> gate_jtd_XOR_qwj
    gate_jtd_XOR_qwj --> z39
    z39[[z39]]
    gate_bqd_AND_qsm[(&)]
    bqd --> gate_bqd_AND_qsm
    qsm --> gate_bqd_AND_qsm
    gate_bqd_AND_qsm --> skc
    skc[[skc]]
    gate_x30_AND_y30[(&)]
    x30 --> gate_x30_AND_y30
    y30 --> gate_x30_AND_y30
    gate_x30_AND_y30 --> hcg
    hcg[[hcg]]
    gate_x12_AND_y12[(&)]
    x12 --> gate_x12_AND_y12
    y12 --> gate_x12_AND_y12
    gate_x12_AND_y12 --> pmr
    pmr[[pmr]]
    gate_x32_XOR_y32[(=1)]
    x32 --> gate_x32_XOR_y32
    y32 --> gate_x32_XOR_y32
    gate_x32_XOR_y32 --> dgk
    dgk[[dgk]]
    gate_y41_AND_x41[(&)]
    y41 --> gate_y41_AND_x41
    x41 --> gate_y41_AND_x41
    gate_y41_AND_x41 --> vqn
    vqn[[vqn]]
    gate_pnf_AND_tmr[(&)]
    pnf --> gate_pnf_AND_tmr
    tmr --> gate_pnf_AND_tmr
    gate_pnf_AND_tmr --> djt
    djt[[djt]]
    gate_dsf_OR_tnt[(≥1)]
    dsf --> gate_dsf_OR_tnt
    tnt --> gate_dsf_OR_tnt
    gate_dsf_OR_tnt --> wpv
    wpv[[wpv]]
    gate_cgf_OR_kgh[(≥1)]
    cgf --> gate_cgf_OR_kgh
    kgh --> gate_cgf_OR_kgh
    gate_cgf_OR_kgh --> pfg
    pfg[[pfg]]
    gate_cdw_OR_mgt[(≥1)]
    cdw --> gate_cdw_OR_mgt
    mgt --> gate_cdw_OR_mgt
    gate_cdw_OR_mgt --> vdb
    vdb[[vdb]]
    gate_mtg_XOR_gbv[(=1)]
    mtg --> gate_mtg_XOR_gbv
    gbv --> gate_mtg_XOR_gbv
    gate_mtg_XOR_gbv --> z18
    z18[[z18]]
    gate_pbq_OR_dpv[(≥1)]
    pbq --> gate_pbq_OR_dpv
    dpv --> gate_pbq_OR_dpv
    gate_pbq_OR_dpv --> tmr
    tmr[[tmr]]
    gate_x25_XOR_y25[(=1)]
    x25 --> gate_x25_XOR_y25
    y25 --> gate_x25_XOR_y25
    gate_x25_XOR_y25 --> hnw
    hnw[[hnw]]
    gate_wdr_OR_htq[(≥1)]
    wdr --> gate_wdr_OR_htq
    htq --> gate_wdr_OR_htq
    gate_wdr_OR_htq --> chd
    chd[[chd]]
    gate_vgj_XOR_pms[(=1)]
    vgj --> gate_vgj_XOR_pms
    pms --> gate_vgj_XOR_pms
    gate_vgj_XOR_pms --> z22
    z22[[z22]]
    gate_x08_XOR_y08[(=1)]
    x08 --> gate_x08_XOR_y08
    y08 --> gate_x08_XOR_y08
    gate_x08_XOR_y08 --> bcp
    bcp[[bcp]]
    gate_bsf_OR_ccs[(≥1)]
    bsf --> gate_bsf_OR_ccs
    ccs --> gate_bsf_OR_ccs
    gate_bsf_OR_ccs --> gqg
    gqg[[gqg]]
    gate_x05_XOR_y05[(=1)]
    x05 --> gate_x05_XOR_y05
    y05 --> gate_x05_XOR_y05
    gate_x05_XOR_y05 --> pnf
    pnf[[pnf]]
    gate_x39_XOR_y39[(=1)]
    x39 --> gate_x39_XOR_y39
    y39 --> gate_x39_XOR_y39
    gate_x39_XOR_y39 --> jtd
    jtd[[jtd]]
    gate_x21_AND_y21[(&)]
    x21 --> gate_x21_AND_y21
    y21 --> gate_x21_AND_y21
    gate_x21_AND_y21 --> jsj
    jsj[[jsj]]
    gate_x07_AND_y07[(&)]
    x07 --> gate_x07_AND_y07
    y07 --> gate_x07_AND_y07
    gate_x07_AND_y07 --> swt
    swt[[swt]]
    gate_x16_XOR_y16[(=1)]
    x16 --> gate_x16_XOR_y16
    y16 --> gate_x16_XOR_y16
    gate_x16_XOR_y16 --> csb
    csb[[csb]]
    gate_mtg_AND_gbv[(&)]
    mtg --> gate_mtg_AND_gbv
    gbv --> gate_mtg_AND_gbv
    gate_mtg_AND_gbv --> ngw
    ngw[[ngw]]
    gate_gvs_XOR_hnw[(=1)]
    gvs --> gate_gvs_XOR_hnw
    hnw --> gate_gvs_XOR_hnw
    gate_gvs_XOR_hnw --> z25
    z25[[z25]]
    gate_gnd_AND_ddh[(&)]
    gnd --> gate_gnd_AND_ddh
    ddh --> gate_gnd_AND_ddh
    gate_gnd_AND_ddh --> vtg
    vtg[[vtg]]
    gate_x38_AND_y38[(&)]
    x38 --> gate_x38_AND_y38
    y38 --> gate_x38_AND_y38
    gate_x38_AND_y38 --> ncq
    ncq[[ncq]]
    gate_btc_OR_pvw[(≥1)]
    btc --> gate_btc_OR_pvw
    pvw --> gate_btc_OR_pvw
    gate_btc_OR_pvw --> shk
    shk[[shk]]
    gate_bqw_AND_mnh[(&)]
    bqw --> gate_bqw_AND_mnh
    mnh --> gate_bqw_AND_mnh
    gate_bqw_AND_mnh --> dsw
    dsw[[dsw]]
    gate_dns_AND_qbf[(&)]
    dns --> gate_dns_AND_qbf
    qbf --> gate_dns_AND_qbf
    gate_dns_AND_qbf --> bwr
    bwr[[bwr]]
    gate_y18_AND_x18[(&)]
    y18 --> gate_y18_AND_x18
    x18 --> gate_y18_AND_x18
    gate_y18_AND_x18 --> srm
    srm[[srm]]
    gate_cwh_AND_wpv[(&)]
    cwh --> gate_cwh_AND_wpv
    wpv --> gate_cwh_AND_wpv
    gate_cwh_AND_wpv --> kmg
    kmg[[kmg]]
    gate_skc_OR_bnc[(≥1)]
    skc --> gate_skc_OR_bnc
    bnc --> gate_skc_OR_bnc
    gate_skc_OR_bnc --> kmm
    kmm[[kmm]]
    gate_x09_AND_y09[(&)]
    x09 --> gate_x09_AND_y09
    y09 --> gate_x09_AND_y09
    gate_x09_AND_y09 --> nnh
    nnh[[nnh]]
    gate_wgq_OR_kmg[(≥1)]
    wgq --> gate_wgq_OR_kmg
    kmg --> gate_wgq_OR_kmg
    gate_wgq_OR_kmg --> rcd
    rcd[[rcd]]
    gate_dtr_XOR_brm[(=1)]
    dtr --> gate_dtr_XOR_brm
    brm --> gate_dtr_XOR_brm
    gate_dtr_XOR_brm --> z38
    z38[[z38]]
    gate_x00_AND_y00[(&)]
    x00 --> gate_x00_AND_y00
    y00 --> gate_x00_AND_y00
    gate_x00_AND_y00 --> brj
    brj[[brj]]
    gate_x19_AND_y19[(&)]
    x19 --> gate_x19_AND_y19
    y19 --> gate_x19_AND_y19
    gate_x19_AND_y19 --> nmm
    nmm[[nmm]]
    gate_kmm_XOR_jfh[(=1)]
    kmm --> gate_kmm_XOR_jfh
    jfh --> gate_kmm_XOR_jfh
    gate_kmm_XOR_jfh --> z43
    z43[[z43]]
    gate_bfg_AND_vcs[(&)]
    bfg --> gate_bfg_AND_vcs
    vcs --> gate_bfg_AND_vcs
    gate_bfg_AND_vcs --> hnh
    hnh[[hnh]]
    gate_dns_XOR_qbf[(=1)]
    dns --> gate_dns_XOR_qbf
    qbf --> gate_dns_XOR_qbf
    gate_dns_XOR_qbf --> z41
    z41[[z41]]
    gate_y22_XOR_x22[(=1)]
    y22 --> gate_y22_XOR_x22
    x22 --> gate_y22_XOR_x22
    gate_y22_XOR_x22 --> pms
    pms[[pms]]
    gate_x23_XOR_y23[(=1)]
    x23 --> gate_x23_XOR_y23
    y23 --> gate_x23_XOR_y23
    gate_x23_XOR_y23 --> hbv
    hbv[[hbv]]
    gate_dfm_AND_ggd[(&)]
    dfm --> gate_dfm_AND_ggd
    ggd --> gate_dfm_AND_ggd
    gate_dfm_AND_ggd --> skw
    skw[[skw]]
    gate_x15_XOR_y15[(=1)]
    x15 --> gate_x15_XOR_y15
    y15 --> gate_x15_XOR_y15
    gate_x15_XOR_y15 --> wph
    wph[[wph]]
    gate_sgv_OR_khs[(≥1)]
    sgv --> gate_sgv_OR_khs
    khs --> gate_sgv_OR_khs
    gate_sgv_OR_khs --> brm
    brm[[brm]]
    gate_mcs_OR_jsj[(≥1)]
    mcs --> gate_mcs_OR_jsj
    jsj --> gate_mcs_OR_jsj
    gate_mcs_OR_jsj --> vgj
    vgj[[vgj]]
    gate_brj_AND_thc[(&)]
    brj --> gate_brj_AND_thc
    thc --> gate_brj_AND_thc
    gate_brj_AND_thc --> ngv
    ngv[[ngv]]
    gate_htd_OR_scm[(≥1)]
    htd --> gate_htd_OR_scm
    scm --> gate_htd_OR_scm
    gate_htd_OR_scm --> gpq
    gpq[[gpq]]
    gate_wsw_XOR_bmc[(=1)]
    wsw --> gate_wsw_XOR_bmc
    bmc --> gate_wsw_XOR_bmc
    gate_wsw_XOR_bmc --> z02
    z02[[z02]]
    gate_x37_XOR_y37[(=1)]
    x37 --> gate_x37_XOR_y37
    y37 --> gate_x37_XOR_y37
    gate_x37_XOR_y37 --> rqt
    rqt[[rqt]]
    gate_swt_OR_ghb[(≥1)]
    swt --> gate_swt_OR_ghb
    ghb --> gate_swt_OR_ghb
    gate_swt_OR_ghb --> rgc
    rgc[[rgc]]
    gate_skt_OR_wpp[(≥1)]
    skt --> gate_skt_OR_wpp
    wpp --> gate_skt_OR_wpp
    gate_skt_OR_wpp --> pqc
    pqc[[pqc]]
    gate_gqg_XOR_bps[(=1)]
    gqg --> gate_gqg_XOR_bps
    bps --> gate_gqg_XOR_bps
    gate_gqg_XOR_bps --> z40
    z40[[z40]]
    gate_y11_XOR_x11[(=1)]
    y11 --> gate_y11_XOR_x11
    x11 --> gate_y11_XOR_x11
    gate_y11_XOR_x11 --> gsf
    gsf[[gsf]]
    gate_x39_AND_y39[(&)]
    x39 --> gate_x39_AND_y39
    y39 --> gate_x39_AND_y39
    gate_x39_AND_y39 --> ccs
    ccs[[ccs]]
    gate_wph_XOR_phn[(=1)]
    wph --> gate_wph_XOR_phn
    phn --> gate_wph_XOR_phn
    gate_wph_XOR_phn --> z15
    z15[[z15]]
    gate_x04_XOR_y04[(=1)]
    x04 --> gate_x04_XOR_y04
    y04 --> gate_x04_XOR_y04
    gate_x04_XOR_y04 --> rkw
    rkw[[rkw]]
    gate_y36_XOR_x36[(=1)]
    y36 --> gate_y36_XOR_x36
    x36 --> gate_y36_XOR_x36
    gate_y36_XOR_x36 --> cwh
    cwh[[cwh]]
    gate_rqt_AND_rcd[(&)]
    rqt --> gate_rqt_AND_rcd
    rcd --> gate_rqt_AND_rcd
    gate_rqt_AND_rcd --> sgv
    sgv[[sgv]]
    gate_y03_AND_x03[(&)]
    y03 --> gate_y03_AND_x03
    x03 --> gate_y03_AND_x03
    gate_y03_AND_x03 --> btc
    btc[[btc]]
    gate_fmg_OR_cjw[(≥1)]
    fmg --> gate_fmg_OR_cjw
    cjw --> gate_fmg_OR_cjw
    gate_fmg_OR_cjw --> pgt
    pgt[[pgt]]
    gate_x28_XOR_y28[(=1)]
    x28 --> gate_x28_XOR_y28
    y28 --> gate_x28_XOR_y28
    gate_x28_XOR_y28 --> qqt
    qqt[[qqt]]
    gate_y35_XOR_x35[(=1)]
    y35 --> gate_y35_XOR_x35
    x35 --> gate_y35_XOR_x35
    gate_y35_XOR_x35 --> qnw
    qnw[[qnw]]
    gate_x41_XOR_y41[(=1)]
    x41 --> gate_x41_XOR_y41
    y41 --> gate_x41_XOR_y41
    gate_x41_XOR_y41 --> dns
    dns[[dns]]
    gate_ngv_OR_hhp[(≥1)]
    ngv --> gate_ngv_OR_hhp
    hhp --> gate_ngv_OR_hhp
    gate_ngv_OR_hhp --> bmc
    bmc[[bmc]]
    gate_wps_XOR_kmn[(=1)]
    wps --> gate_wps_XOR_kmn
    kmn --> gate_wps_XOR_kmn
    gate_wps_XOR_kmn --> z03
    z03[[z03]]
    gate_cms_OR_qdw[(≥1)]
    cms --> gate_cms_OR_qdw
    qdw --> gate_cms_OR_qdw
    gate_cms_OR_qdw --> ktp
    ktp[[ktp]]
    gate_ktp_XOR_rjm[(=1)]
    ktp --> gate_ktp_XOR_rjm
    rjm --> gate_ktp_XOR_rjm
    gate_ktp_XOR_rjm --> z24
    z24[[z24]]
    gate_rvc_AND_kpv[(&)]
    rvc --> gate_rvc_AND_kpv
    kpv --> gate_rvc_AND_kpv
    gate_rvc_AND_kpv --> ghb
    ghb[[ghb]]
    gate_vdd_XOR_dgk[(=1)]
    vdd --> gate_vdd_XOR_dgk
    dgk --> gate_vdd_XOR_dgk
    gate_vdd_XOR_dgk --> z32
    z32[[z32]]
    gate_vpv_XOR_ddq[(=1)]
    vpv --> gate_vpv_XOR_ddq
    ddq --> gate_vpv_XOR_ddq
    gate_vpv_XOR_ddq --> z09
    z09[[z09]]
    gate_x10_AND_y10[(&)]
    x10 --> gate_x10_AND_y10
    y10 --> gate_x10_AND_y10
    gate_x10_AND_y10 --> pgp
    pgp[[pgp]]
    gate_psj_AND_qbn[(&)]
    psj --> gate_psj_AND_qbn
    qbn --> gate_psj_AND_qbn
    gate_psj_AND_qbn --> cth
    cth[[cth]]
    gate_pgp_OR_skw[(≥1)]
    pgp --> gate_pgp_OR_skw
    skw --> gate_pgp_OR_skw
    gate_pgp_OR_skw --> cft
    cft[[cft]]
    gate_x24_AND_y24[(&)]
    x24 --> gate_x24_AND_y24
    y24 --> gate_x24_AND_y24
    gate_x24_AND_y24 --> wsv
    wsv[[wsv]]
    gate_y40_AND_x40[(&)]
    y40 --> gate_y40_AND_x40
    x40 --> gate_y40_AND_x40
    gate_y40_AND_x40 --> rbw
    rbw[[rbw]]
    gate_y07_XOR_x07[(=1)]
    y07 --> gate_y07_XOR_x07
    x07 --> gate_y07_XOR_x07
    gate_y07_XOR_x07 --> kpv
    kpv[[kpv]]
    gate_y36_AND_x36[(&)]
    y36 --> gate_y36_AND_x36
    x36 --> gate_y36_AND_x36
    gate_y36_AND_x36 --> wgq
    wgq[[wgq]]
    gate_y01_XOR_x01[(=1)]
    y01 --> gate_y01_XOR_x01
    x01 --> gate_y01_XOR_x01
    gate_y01_XOR_x01 --> thc
    thc[[thc]]
    gate_pgt_AND_hbv[(&)]
    pgt --> gate_pgt_AND_hbv
    hbv --> gate_pgt_AND_hbv
    gate_pgt_AND_hbv --> qdw
    qdw[[qdw]]
    gate_y09_XOR_x09[(=1)]
    y09 --> gate_y09_XOR_x09
    x09 --> gate_y09_XOR_x09
    gate_y09_XOR_x09 --> vpv
    vpv[[vpv]]
    gate_hnh_OR_vfn[(≥1)]
    hnh --> gate_hnh_OR_vfn
    vfn --> gate_hnh_OR_vfn
    gate_hnh_OR_vfn --> mtg
    mtg[[mtg]]
    gate_dwq_XOR_pgq[(=1)]
    dwq --> gate_dwq_XOR_pgq
    pgq --> gate_dwq_XOR_pgq
    gate_dwq_XOR_pgq --> z13
    z13[[z13]]
    gate_wsv_OR_pwn[(≥1)]
    wsv --> gate_wsv_OR_pwn
    pwn --> gate_wsv_OR_pwn
    gate_wsv_OR_pwn --> gvs
    gvs[[gvs]]
    gate_x33_AND_y33[(&)]
    x33 --> gate_x33_AND_y33
    y33 --> gate_x33_AND_y33
    gate_x33_AND_y33 --> vjs
    vjs[[vjs]]
    gate_gnd_XOR_ddh[(=1)]
    gnd --> gate_gnd_XOR_ddh
    ddh --> gate_gnd_XOR_ddh
    gate_gnd_XOR_ddh --> z20
    z20[[z20]]
    gate_y29_XOR_x29[(=1)]
    y29 --> gate_y29_XOR_x29
    x29 --> gate_y29_XOR_x29
    gate_y29_XOR_x29 --> qbn
    qbn[[qbn]]
    gate_dmw_OR_sbq[(≥1)]
    dmw --> gate_dmw_OR_sbq
    sbq --> gate_dmw_OR_sbq
    gate_dmw_OR_sbq --> rtm
    rtm[[rtm]]
    gate_gqg_AND_bps[(&)]
    gqg --> gate_gqg_AND_bps
    bps --> gate_gqg_AND_bps
    gate_gqg_AND_bps --> cff
    cff[[cff]]
    gate_mnh_XOR_bqw[(=1)]
    mnh --> gate_mnh_XOR_bqw
    bqw --> gate_mnh_XOR_bqw
    gate_mnh_XOR_bqw --> z12
    z12[[z12]]
    gate_rrf_AND_qnw[(&)]
    rrf --> gate_rrf_AND_qnw
    qnw --> gate_rrf_AND_qnw
    gate_rrf_AND_qnw --> dsf
    dsf[[dsf]]